### ISSUE TITLE
How to Run Single Iteration?

### ISSUE THREAD

**Issue by benmarten** [grawk/grunt-loop-mocha#23]
Is it possible to run a single iteration?

e.g. i have this object:

	iterations: [{
		description: 'PhantomJS',
		NODE_ENV: 'config-phantomjs'
	},{
		description: 'Firefox',
		NODE_ENV: 'config-firefox'
	}]

How can i only run Firefox?

**Comment by grawk** [comment]
If you only want to run a single iteration, then create a task configuration with a single iteration. There is no feature for running only a single iteration from a task configuration with more than one.

**Comment by benmarten** [comment]
ok, thanks
